// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutoTest.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ma trận kiểm thử tự động toàn diện")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MaTrậnKiểmThửTựDộngToanDiệnFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Ma trận kiểm thử tự động toàn diện", "  Các testcase này bổ sung phạm vi chức năng và phi chức năng để tổng bộ Reqnroll" +
                " đạt khoảng 100 scenario.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ComprehensiveMatrix.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
  #line hidden
#line 5
    await testRunner.GivenAsync("backend dang san sang", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.AndAsync("he thong du lieu demo duoc reset", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ma trận kiểm thử <id> - <tieu_de>")]
        [NUnit.Framework.TestCaseAttribute("AUTO-001", "Đăng nhập nhân viên hợp lệ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-002", "Đăng nhập admin hợp lệ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-003", "Đăng nhập khách hàng hợp lệ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-004", "Từ chối mật khẩu sai của nhân viên", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-005", "Từ chối mật khẩu sai của khách hàng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-006", "Từ chối tài khoản nhân viên đã khóa", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-007", "Tài khoản nhân viên quyền admin đăng nhập", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-008", "Tự sinh username không trùng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-009", "Bootstrap khách hàng trả về bàn và món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-010", "Bootstrap khách hàng không tồn tại", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-011", "Danh sách đặt bàn của khách seed", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-012", "Khách đặt bàn trống thành công", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-013", "Khách không đặt được bàn đang dùng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-014", "Khách gọi món rỗng bị từ chối", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-015", "Khách tạo hóa đơn web", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-016", "Khách gọi thêm món vào hóa đơn mở", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-017", "Khách khác không dùng bàn đang mở hóa đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-018", "Khách xem lịch sử hóa đơn đã thanh toán", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-019", "Danh sách bàn seed có 16 bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-020", "Tạo bàn mới", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-021", "Cập nhật thông tin bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-022", "Xóa bàn trống", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-023", "Không xóa bàn có hóa đơn mở", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-024", "Bao phủ trạng thái bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-025", "Hóa đơn mở gắn activeOrderId vào bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-026", "Reset khôi phục số bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-027", "Danh sách thực đơn seed có 52 món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-028", "Tạo món mặc định", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-029", "Tạo món tùy chỉnh", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-030", "Cập nhật giá món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-031", "Ẩn món khỏi thực đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-032", "Xóa món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-033", "Món bị ẩn không hiện ở web khách", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-034", "Không gọi được món bị ẩn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-035", "Danh sách hóa đơn seed", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-036", "Nhân viên tạo hóa đơn mở", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-037", "Lấy hóa đơn mở theo bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-038", "Tái sử dụng hóa đơn mở cùng bàn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-039", "Thêm batch món vào hóa đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-040", "Thêm một dòng món vào hóa đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-041", "Cập nhật số lượng món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-042", "Số lượng bằng 0 xóa dòng món", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-043", "Thanh toán hóa đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-044", "Không cho vai trò sai thu tiền", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-045", "Ghi công nợ hóa đơn", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-046", "Lọc hóa đơn đã thanh toán", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-047", "Danh sách công nợ seed", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-048", "Lọc công nợ mở", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-049", "Thanh toán công nợ một phần", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-050", "Thanh toán hết công nợ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-051", "Công nợ không tồn tại trả lỗi", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-052", "Vai trò sai không thu công nợ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-053", "Danh sách nhân viên seed", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-054", "Tạo nhân viên kèm tài khoản", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-055", "Username nhân viên không trùng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-056", "Cập nhật hồ sơ nhân viên", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-057", "Khóa nhân viên", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-058", "Tài khoản bị khóa không đăng nhập", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-059", "Tạo nhân viên quyền admin", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-060", "API nhân viên không lộ password", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-061", "Lấy chấm công theo ngày", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-062", "Check-in nhân viên", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-063", "Check-in cùng ngày không tạo trùng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-064", "Check-out nhân viên", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-065", "Check-out id không tồn tại trả lỗi", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-066", "Bảng lương tháng có dữ liệu", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-067", "Dashboard trả về số liệu tổng quan", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-068", "Dashboard giới hạn dữ liệu gần đây", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-069", "Thống kê ngày", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-070", "Thống kê tháng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-071", "Thống kê năm", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-072", "Payroll đúng tháng yêu cầu", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-073", "Admin health", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-074", "Admin export đủ collection", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-075", "Admin reset khôi phục seed", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-076", "Tạo thông báo", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-077", "Xóa thông báo", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-078", "Web khách được phục vụ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-079", "Web nhân viên được phục vụ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-080", "Web admin được phục vụ", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-081", "API root sẵn sàng", null)]
        [NUnit.Framework.TestCaseAttribute("AUTO-082", "Dashboard phản hồi dưới ngưỡng", null)]
        public async System.Threading.Tasks.Task MaTrậnKiểmThửId_Tieu_De(string id, string tieu_De, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("id", id);
            argumentsOfScenario.Add("tieu_de", tieu_De);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ma trận kiểm thử <id> - <tieu_de>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 9
    await testRunner.WhenAsync(string.Format("tôi chạy testcase tự động \"{0}\"", id), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync(string.Format("testcase \"{0}\" đạt yêu cầu", id), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
